site_name: Frank's Game Reviews
theme:
    name: dracula
    favicon: favicon.png
    logo: favicon.png


markdown_extensions:
  - attr_list

nav:
  - Home: 'index.md'
  - 'Ranked By Score': 'RankedByScore.md'
  - '2024':
    - 'Dave The Diver': '2024/DaveTheDiver.md'
    - 'Prince of Persia: The Lost Crown': '2024/PrinceOfPersia.md'
    - 'LEGO Star Wars: The Skywalker Saga': '2024/LegoStarWars.md'
  - '2023':
    - 'God Of War (2018)': '2023/GodOfWar.md'
    - 'Civilization VI': '2023/Civ6.md'
    - 'Final Fantasy VII Remake': '2023/FF7R.md'
    - 'Valheim': '2023/Valheim.md'
    - 'Elden Ring NG+': '2023/EldenRingNGPlus.md'
    - 'Diablo IV': '2023/DiabloIV.md'
    - 'Red Dead Redemption 2': '2023/RedDeadRedemption2.md'
    - 'Titanfall 2': '2023/Titanfall2.md'
    - 'Spider-Man Remastered': '2023/SpiderMan.md'
    - "Baldur's Gate 3": '2023/BaldursGate3.md'
    - "Dead Cells": '2023/DeadCells.md'
    - "V Rising": '2023/VRising.md'
    - 'NARUTO SHIPPUDEN ULTIMATE NINJA STORM 4': '2023/Naruto.md'
    - 'Portal 2 Coop': '2023/Portal2.md'
  - '2022':
    - 'Deep Rock Galactic': '2022/DeepRockGalactic.md'
    - 'Loop Hero': '2022/LoopHero.md'
    - "Death's Door": '2022/DeathsDoor.md'
    - "Vampire Survivors": '2022/VampireSurvivors.md'
    - "Elden Ring": '2022/EldenRing.md'
    - "FFXIV: Endwalker": '2022/Endwalker.md'
    - "Roller Champions": '2022/RollerChampions.md'
    - "Trackmania": '2022/Trackmania.md'
    - "Multiversus": '2022/Multiversus.md'
    - "Farcry 6": '2022/Farcry6.md'
    - "Inscryption": '2022/Inscryption.md'
  - '2021':
    - 'Doom Eternal': '2021/DoomEternal.md'
    - 'Risk of Rain 2': '2021/RiskOfRain2.md'
    - 'Hades': '2021/Hades.md'
    - 'Dark Souls 3': '2021/DarkSouls3.md'
    - 'Star Wars: Battlefront II': '2021/Battlefront2.md'
    - 'For Honor': '2021/ForHonor.md'
    - 'Inside': '2021/Inside.md'
    - 'Sekiro': '2021/Sekiro.md'
    - 'Ori: And the Blind Forest': '2021/Ori.md'
    - 'Divinity: Original Sin II': '2021/Divinity2.md'
    - 'Going Under': '2021/GoingUnder.md'
    - 'FFXIV: Heavensward': '2021/Heavensward.md'
    - 'FFXIV: Stormblood': '2021/Stormblood.md'
    - 'FFXIV: Shadowbringers': '2021/Shadowbringers.md'
    - 'Halo Infinite': '2021/HaloInfinite.md'
    - 'Control': '2021/Control.md'
    