site_name: Frank's Game Reviews
theme:
    name: dracula

markdown_extensions:
  - attr_list

nav:
  - Home: 'index.md'
  - '2024':
    - 'Dave The Diver': '2024/DaveTheDiver.md'
    - 'Prince of Persia: The Lost Crown': '2024/PrinceOfPersia.md'
    - 'LEGO Star Wars: The Skywalker Saga': '2024/LegoStarWars.md'